general:
  make_log: True
  debug: False
  exp_name: baseline
  num_exp: 1
inference_dir: inference_img/
param_yaml: 'yeominrak_feature_ratio.yaml'

dataset_class: SamplingScore
model_class: QkvRollSeq2seq


data:
  use_pitch_modification: True
  modification_ratio: 0.3
  min_meas: 4
  max_meas: 4
  sampling_rate: 2

model:
  features:
    - index
    - pitch
  #   - offset
  #   - dynamic
  #   - measure_idx
  #   # - measure_change
  emb:
    emb_size: 128
    index: 0.25
    pitch: 0.75
    dynamic: 0.25
    offset: 0.5
    total_size: 0
  gru:
    hidden_size: 128
    num_layers: 2
    dropout: 0.1
  sampling_rate: 2
train:
  batch_size: 64
  # total_iters: 25000
  num_epoch: 600
  seed: 42
  num_workers: 8
  lr: 1e-3



  
  

