general:
  make_log: False
  debug: False
  exp_name: baseline
  num_exp: 1
  entity: null
  project: six-dragons-fly-again
inference_dir: inference_img/

dataset_class: JGMaskedDataset
model_class: JeongganBERT
loss_fn: nll_loss_bert
collate_fn: pad_collate_transformer
trainer_class: BertTrainer
data:
  # use_pitch_modification: true
  # modification_ratio: 0.3
  # min_meas: 4
  # max_meas: 4
  # sampling_rate: 2
  # target_instrument: 0
  slice_measure_num: 4
  num_max_inst: 1
  use_jangdan: False
  use_genre: False
  is_pos_counter: True
model:
  dim: 128
  depth: 12
  num_heads: 4
  dropout: 0.2
  is_pos_enc: false
train:
  batch_size: 16
  num_epoch: 400
  seed: 42
  num_workers: 4
  lr: 0.001
aug:
  entire_orn_r: 0.5
  jg_r: 0.15
  frame_replace_r: 0.05
  frame_rand_r: 0.05
  mask_note_r: 0.2
  replace_note_r: 0.1
  erase_note_r: 0.1
