general:
  make_log: True
  debug: False
  exp_name: baseline
  num_exp: 1
  entity: danbinaerin
  project: yeominrak
inference_dir: inference_img/
param_yaml: 'yeominrak_feature_ratio.yaml'

dataset_class: JeongganDataset #ABCDataset
model_class: JeongganTransSeq2seq
loss_fn: nll_loss_transformer_with_logsoftmax
collate_fn: pad_collate_transformer
trainer_class: JeongganTrainer



data:
  use_pitch_modification: True
  modification_ratio: 0.3
  min_meas: 4
  max_meas: 4
  sampling_rate: 2
  target_instrument: 0
  # is_pos_counter: True
  is_pos_counter: True
  num_max_inst: 4
  use_offset: False
  summarize_position: False

model:
  dim: 64
  depth: 4
  num_heads: 4
  dropout: 0.2
  # is_pos_enc: False
  is_pos_enc: False

train:
  batch_size: 16
  # total_iters: 25000
  num_epoch: 300
  seed: 42
  num_workers: 8
  lr: 1e-3

aug: null


